# Generated by Django 3.2.3 on 2021-05-19 00:53

import daily_focus.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('左侧围分装线', '左侧围分装线'), ('前地板分装线', '前地板分装线'), ('右侧围自动线', '右侧围自动线'), ('机舱自动线', '机舱自动线'), ('右侧围分装线', '右侧围分装线'), ('后地板分装线', '后地板分装线'), ('左前门', '左前门'), ('右前门', '右前门'), ('MB2线', 'MB2线'), ('行李箱盖', '行李箱盖'), ('最终线', '最终线'), ('空气室分装线', '空气室分装线'), ('右后门', '右后门'), ('MB1线', 'MB1线'), ('CO2焊', 'CO2焊'), ('前围板分装线', '前围板分装线'), ('前纵梁线', '前纵梁线'), ('装调线', '装调线'), ('左侧围自动线', '左侧围自动线'), ('顶盖', '顶盖'), ('左后门', '左后门'), ('发盖', '发盖'), ('UB线', 'UB线')], max_length=300, verbose_name='线体')),
                ('station', models.CharField(blank=True, max_length=300, verbose_name='工位')),
                ('focus_content', models.TextField(blank=True, verbose_name='关注内容')),
                ('focus_start', models.DateField(verbose_name='关注开始')),
                ('focus_end', models.DateField(verbose_name='关注结束')),
                ('last_modify', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='focus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-focus_end'],
            },
        ),
        migrations.CreateModel(
            name='FocusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=daily_focus.models.user_directory_path)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('focus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='daily_focus.focus')),
            ],
        ),
        migrations.CreateModel(
            name='FocusAfterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=daily_focus.models.user_directory_path)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('focus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_images', to='daily_focus.focus')),
            ],
        ),
    ]
